[package]
name = "kwik"
version = "1.17.3"
edition = "2024"

[dependencies]
csv = "1.3.1"
gnuplot = "0.0.46"
indexmap = "2.9.0"
md-5 = "0.10.6"
num-format = "0.4.4"
num-traits = "0.2.19"
rand = { version = "0.9.1", features = ["small_rng"] }
rayon = "1.10.0"
sha2 = "0.10.9"
statrs = "0.18.0"
sysinfo = "0.33.1"
thiserror = "2.0.12"
nohash-hasher = "0.2.0"
linreg = "0.2.0"
parking_lot = "0.12.3"

[dev-dependencies]
approx = "0.5.1"
