[package]
name = "kwik"
version = "1.12.6"
edition = "2021"

[dependencies]
csv = "1.3.1"
gnuplot = "0.0.44"
indexmap = "2.6.0"
md-5 = "0.10.6"
num-format = "0.4.4"
num-traits = "0.2.19"
rand = { version = "0.8.5", "features" = ["small_rng"] }
rayon = "1.10.0"
sha2 = "0.10.8"
statrs = "0.17.1"
sysinfo = "0.32.0"
thiserror = "2.0.3"
