[package]
name = "kwik"
version = "1.6.1"
edition = "2021"

[dependencies]
csv = "1.3.0"
gnuplot = "0.0.43"
indexmap = "2.2.6"
md-5 = "0.10.6"
num-format = "0.4.4"
rand = { version = "0.8.5", "features" = ["small_rng"] }
rayon = "1.10.0"
sha2 = "0.10.8"
statrs = "0.16.0"
sysinfo = "0.30.12"
thiserror = "1.0.60"
